name: Audit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - "**/package.json"
      - "**/yarn.lock"

jobs:
  audit-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rust audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  audit-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn audit
        working-directory: cli/tauri.js
        run: yarn audit
